package Json

import (
	"encoding/json"
	"fmt"
	"log"
)

type AutoGenerated struct {
	Age   string `json:"age"`
	Name  string `json:"name"`
	Other struct {
		Addr  string `json:"addr"`
		Phone string `json:"phone"`
	} `json:"other"`
}

func main(){
	var c AutoGenerated
	var JSON = `{"age":"20","name":"lws","other":{"addr":"china","phone":"123456"}}`
	err := json.Unmarshal([]byte(JSON), &c)	//json转化为结构体
	if err != nil {
		log.Println("ERROR:", err)
		return
	}
	fmt.Println(c)
	fmt.Println(c.Name)
	fmt.Println(c.Other.Addr)
}